init library
wikibusiness/aiohttp-flashbag pull request #1
Opened 2017-11-16 15:26 UTC by froosty

2017-11-17 13:19 UTC, asvetlov requested changes

2017-11-17 13:19 UTC, asvetlov commented on README.rst
> +.. _aiohttp_web: https://aiohttp.readthedocs.io/en/latest/web.html
https://docs.aiohttp.org/en/stable/ :)

2017-11-17 13:19 UTC, asvetlov commented on aiohttp_flashbag/__init__.py
> +    print('=' * 100)
`print()`?

2017-11-17 13:19 UTC, asvetlov commented on setup.py
> +        os.path.join(
`pathlib` looks better

2017-11-17 14:12 UTC, asvetlov approved these changes

2017-11-20 19:21 UTC, roganov commented on README.rst
> +For specify one "variable" in flashbag you should use ``aiohttp_flashbag.flashbag_set``. Parameters:
For -> To
Or better yet 'To set'.

2017-11-20 19:21 UTC, roganov commented on README.rst
> +- **key**. Name of "variable", that you want to get
Extra comma

2017-11-20 19:21 UTC, roganov commented on README.rst
> +- **key**. Name of "variable", that you want to specify.
Extra comma

2017-11-20 19:21 UTC, roganov commented on aiohttp_flashbag/__init__.py
> +    return request[OLD_REQUEST_KEY].pop(key, default)
Why pop?

2017-11-29 10:43 UTC, merged